// tailwind.config.cjs
const cssRgb = (name) => `rgb(var(${name}) / <alpha-value>)`;

module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx,html}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        secondary: cssRgb('--color-secondary-rgb'),
        'secondary-container': cssRgb('--color-secondary-100-rgb'),
        'secondary-fixed': cssRgb('--color-secondary-100-rgb'),
        'secondary-fixed-dim': cssRgb('--color-secondary-300-rgb'),
        'on-secondary-fixed': cssRgb('--color-secondary-900-rgb'),
        'on-secondary-fixed-variant': cssRgb('--color-secondary-800-rgb'),
        'on-secondary-container': cssRgb('--color-secondary-800-rgb'),
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#7ed99e',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'primary-fixed': cssRgb('--color-primary-100-rgb'),
        error: '#ba1a1a',
        'primary-fixed-dim': cssRgb('--color-primary-200-rgb'),
        'on-primary-fixed-variant': cssRgb('--color-primary-900-rgb'),
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed': '#9af6b8',
        'on-background': '#191c1e',
        tertiary: '#000803',
        'outline-variant': cssRgb('--color-border-rgb'),
        'surface-container': '#eceef0',
        'on-tertiary-container': '#3c9762',
        'inverse-primary': cssRgb('--color-primary-200-rgb'),
        'surface-bright': '#f7f9fb',
        primary: cssRgb('--color-primary-rgb'),
        'primary-container': cssRgb('--color-primary-100-rgb'),
        'tertiary-container': '#002511',
        'surface-dim': '#d8dadc',
        'inverse-on-surface': '#eff1f3',
        'on-primary': cssRgb('--color-on-primary-rgb'),
        'on-error-container': '#93000a',
        'surface-container-highest': '#e0e3e5',
        'surface-tint': '#476083',
        'surface-container-high': '#e6e8ea',
        'on-primary-container': cssRgb('--color-primary-900-rgb'),
        'on-primary-fixed': cssRgb('--color-primary-900-rgb'),
        outline: '#74777f',
        'on-tertiary-fixed': '#00210f',
        'inverse-surface': '#2d3133',
        'surface-variant': '#e0e3e5',
        'surface-container-low': '#f2f4f6',
        background: cssRgb('--color-background-rgb'),
        surface: cssRgb('--color-surface-rgb'),
        'on-tertiary-fixed-variant': '#00522d',
        'on-surface': cssRgb('--color-text-rgb'),
        'on-surface-variant': cssRgb('--color-text-secondary-rgb'),
        'indigo-50': cssRgb('--color-indigo-50-rgb'),
        'indigo-100': cssRgb('--color-indigo-100-rgb'),
        'indigo-200': cssRgb('--color-indigo-200-rgb'),
        'indigo-300': cssRgb('--color-indigo-300-rgb'),
        'indigo-400': cssRgb('--color-indigo-400-rgb'),
        'indigo-500': cssRgb('--color-indigo-500-rgb'),
        'indigo-600': cssRgb('--color-indigo-600-rgb'),
        'indigo-700': cssRgb('--color-indigo-700-rgb'),
        'indigo-800': cssRgb('--color-indigo-800-rgb'),
        'indigo-900': cssRgb('--color-indigo-900-rgb'),
      },
      borderRadius: {
        DEFAULT: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        md: '16px',
        sm: '8px',
        base: '8px',
        gutter: '16px',
        xs: '4px',
        xl: '40px',
        lg: '24px',
        'container-margin': '24px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'title-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-md': ['17px', { lineHeight: '26px', fontWeight: '400' }],
        'display-lg': [
          '36px',
          {
            lineHeight: '44px',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
        'headline-sm': ['22px', { lineHeight: '30px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-md': [
          '14px',
          {
            lineHeight: '20px',
            letterSpacing: '0.03em',
            fontWeight: '600',
          },
        ],
        'headline-md': [
          '28px',
          {
            lineHeight: '36px',
            letterSpacing: '-0.01em',
            fontWeight: '700',
          },
        ],
      },
    },
  },
  plugins: [],
};
